version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: auctionverse-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auctionverse
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
