services:
  - type: web
    name: auctionverse-3
    env: static
    branch: vanilla-version
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
